version: '3.3'
services:
  #  web:
  #    image: io.fls/blogapp:latest
  #    ports:
  #      - 8085:8085
  #    restart: always
  #    depends_on:
  #      - mongo
  #    environment:
  #      MONGODB_HOST: mongo
  #    networks:
  #      - database

  mongo:
    image: mongo
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: blog
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - database

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: blog
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - database

  # https://github.com/alexei-led/pumba
  # Needs $Env:COMPOSE_CONVERT_WINDOWS_PATHS=1 an Windows
#  chaos-delay:
#    image: gaiaadm/pumba
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    command: "--log-level debug --interval 30s netem --tc-image gaiadocker/iproute2 --duration 15s delay --time 1000 re2:web"

networks:
  database:
